#################################################################
## HASS related
#################################################################
- id: hass_start_notification
  alias: NOTIFY (START) Home Assistant
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.mobile_app_william
    data:
      title: ''
      message: Home Assistant Started

- id: 'sync_bedroom_lamp_state'
  alias: "Sync Bedroom Lamps States"
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "tasmotas/cmnd/state"
        payload: ""

#################################################################
## Presence detection
#################################################################
- id: notify_resident_emily
  alias: NOTIFY (Location) Resident
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  trigger:
  - platform: state
    entity_id: person.emily
  action:
  - service: notify.mobile_app_william
    data_template:
      message: '{{ trigger.from_state.attributes.friendly_name }} is {% if trigger.to_state.state == ''home'' %}at home{% elif trigger.to_state.state == ''not_home'' %}away{%else %}at {{ trigger.to_state.state }}{% endif %}.'

- id: notify_resident_william
  alias: NOTIFY (Location) Resident
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  trigger:
  - platform: state
    entity_id: person.william
  action:
  - service: notify.mobile_app_emily
    data_template:
      message: '{{ trigger.from_state.attributes.friendly_name }} is {% if trigger.to_state.state == ''home'' %}at home{% elif trigger.to_state.state == ''not_home'' %}away{%else %}at {{ trigger.to_state.state }}{% endif %}.'

- id: request_location_update
  alias: Request Location Update
  trigger:
  - platform: state
    entity_id: input_boolean.locaion_update
    to: 'on'
  action:
  - service: notify.all_devices
    data:
      message: request_locaiton_update

- id: reset_location_update
  alias: Reset Location Update
  trigger:
  - platform: state
    entity_id: input_boolean.locaion_update
    to: 'on'
    for:
      seconds: 5
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.locaion_update
#################################################################
## Door Notifications
#################################################################
- id: notify_garage_door
  alias: Notify Garage door
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
  action:
  - service: notify.all_devices
    data_template:
      message: '{{ trigger.from_state.attributes.friendly_name }} is {% if trigger.to_state.state == ''off'' %}closed{% else %}open{% endif %}.'

- id: notify_garage_open_10_min
  alias: Notify Garage open for 10 min
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
    to: 'on'
    for:
      minutes: 10
  action:
  - service: notify.all_devices
    data:
      message: Garage door has been open for 10 minutes! Close it!

#################################################################
## Home Security
#################################################################
- id: alarm_triggered_away
  alias: Trigger alarm while armed away
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_sensor_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.garage_door
    to: 'on'
  - platform: state
    entity_id: binary_sensor.back_door
    to: 'on'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm

- id: alarm_notify
  alias: Send notification when alarm triggered
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  action:
  - service: notify.all_devices
    data:
      message: ALARM! The alarm has been triggered at {{ states('sensor.date_time') }}
  - service: tts.google_say
    entity_id: media_player.kitchen_display
    data:
      message: Warning. Please leave the premesis. Police have been notified.
  - service: light.turn_on
    data:
      entity_id:
      - light.kitchen_pendant_lights
      - light.lounge_room_lamp
      - light.55404001dc4f22ac01ca
      - light.bedroom_lamp_left
      - light.ollie_s_lamp
      - light.teddy_s_lamp
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 0
      flash: long

- id: alarm_notify_disarmed
  alias: Send notification when alarm is Disarmed
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: disarmed
  action:
  - service: tts.google_say
    entity_id: media_player.kitchen_display
    data:
      message: Alarm is now disarmed.
  - service: notify.all_devices
    data_template:
      message: The alarm is now Disarmed. {{ states('sensor.date_time') }}

- id: alarm_notify_pending
  alias: Send notification when alarm is in pending status
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: pending
  action:
  - service: notify.all_devices
    data_template:
      message: The alarm is in pending status. {{ states('sensor.date_time') }}

- id: alarm_notify_armed_away
  alias: Send notification when alarm is Armed in Away mode
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: armed_away
  action:
  - service: tts.google_say
    entity_id: media_player.kitchen_display
    data:
      message: Alarm has been armed.
  - service: notify.all_devices
    data_template:
      message: 'Alarm is now armed. {{ states(''sensor.date_time'') }}'

- id: alarm_notify_armed_home
  alias: Send notification when alarm is Armed in Home mode
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: armed_home
  action:
  - service: notify.all_devices
    data_template:
      message: 'Alarm is now armed. {{ states(''sensor.date_time'') }}'

- id: alarm_disable_when_arriving
  alias: Alarm disarm when return home
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: pending
  trigger:
  - platform: state
    entity_id: person.william
    from: not_home
    to: home
  - platform: state
    entity_id: person.emily
    from: not_home
    to: home
  action:
  - service: notify.all_devices
    data_template:
      message: Disarming the alarm at {{ states('sensor.date_time') }}
  - service: tts.google_say
    entity_id: media_player.kitchen_display
    data:
      message: Disarming Alarm.
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code

- id: arm_alarm_when_away
  alias: Arm alarm when away and not armed
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  trigger:
  - platform: state
    entity_id: group.household
    to: not_home
    for:
      minutes: 15
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm

- id: mobile_action_arm_alarm
  alias: Arm Alarm from Notificaiton Action
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: arm_alarm
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm

#################################################################
## Object Detection
#################################################################
- id: front_door_object_detection
  alias: Detect Object at the front door
  trigger:
  - entity_id: binary_sensor.front_door_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.front_door
      filename: /config/www/tmp/image.jpg
  - delay: 00:00:03
  - service: image_processing.scan
    entity_id: image_processing.deepstack_detector
  - service: image_processing.scan
    entity_id: image_processing.facebox_saved_image

- id: face_recognised
  alias: Face recognised
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
    platform: event
    event_type: image_processing.detect_face
  action:
    - service_template: >-
        {% if not is_state('sensor.front_door_detection' , 'unavailable') %} 
        notify.all_devices
        {% endif %}
      data_template:
        message: "{{ states('sensor.front_door_detection') }} is at the front door"
        data:
          image: !secret temp_image
          clickAction: !secret motioneye_stream
          actions:
            - action: "URI"
              title: View Image
              uri: !secret temp_image
    - service_template: >-
        {% if not is_state('sensor.front_door_detection' , 'unavailable') %}
        tts.google_say
        {% endif %}
      data_template:
        entity_id: media_player.kitchen_display
        message: "{{ states('sensor.front_door_detection') }} is at the front door"

- id: person_detection
  alias: Notify when person detected
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.options_notifications_push
    state: 'on'
  trigger:
  - platform: event
    event_type: deepstack.object_detected
    event_data:
      object: person
  - platform: event
    event_type: deepstack.object_detected
    event_data:
      object: car
  action:
  - service: notify.all_devices
    data_template:
      message: '{{ trigger.event.data.object | title }} detected {% if trigger.event.data.object == ''person'' %}at the front door{% else %}in the driveway{% endif %}.'
      data:
        image: !secret deepstack_latest_person
        clickAction: !secret motioneye_stream
        actions:
        - action: "URI"
          title: View Image
          uri: !secret deepstack_latest_person

#################################################################
## Light Automations
#################################################################
- id: turn_on_kitchen_pendant_lights_when_motion_detected
  alias: Turn on kitchen lights when lumens are low and motion detected
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_sensor_motion
    to: 'on'
  condition:
  - condition: time
    after: 06:00:00
    before: '18:30:00'
  - condition: numeric_state
    entity_id: sensor.kitchen_sensor_illuminance
    below: '250'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_pendant_lights
        brightness_pct: 100
        color_temp: 1000
    - service: light.turn_on
      data:
        entity_id: light.kitchen_downlight
        brightness_pct: 100
        color_temp: 460

- id: dim-lights-after-10min
  alias: Dim lights after 10min
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_sensor_motion
    to: 'off'
    for: 0:10:00
  condition:
  - condition: time
    after: 06:00:00
    before: '19:50:00'
  - condition: state
    entity_id: light.kitchen_pendant_lights
    state: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.kitchen_dim
    
- id: turn_off_kitchen_pendant_lights_when_lumens_high
  alias: Turn off kitchen lights when lumens are high
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.kitchen_sensor_illuminance
    above: '280'
    for:
      minutes: 3
  condition:
  - condition: time
    after: '06:00:00'
    before: '18:30:00'
  action:
  - service: light.turn_off
    entity_id: light.kitchen_pendant_lights
  - service: light.turn_off
    entity_id: light.kitchen_downlight
    
- id: light_on_at_sunset
  alias: Turn on all lights at sunset
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: group.household
    state: home
  trigger:
    platform: sun
    event: sunset
    offset: "-02:00:00"
  action:
  - service: scene.turn_on
    entity_id: scene.bright_lights
  - service: scene.turn_on
    entity_id: scene.bedroom_lamps_bright
  - service: light.turn_on
    data:
      entity_id: light.lounge_room_lamp
      brightness_pct: 100
      xy_color:
        - 0.388
        - 0.401

- id: turn_on_kitchen_pendant_lights_when_movement_detected
  alias: Turn on Kitchen Lights when movement is detected
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_sensor_motion
    to: 'on'
  condition:
  - condition: time
    after: '18:30:00'
    before: '19:50:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_pendant_lights
        brightness_pct : 40
    - service: light.turn_on
      data:
        entity_id: light.kitchen_downlight
        brightness_pct: 40

    
- id: turn_off_kitchen_pendant_lights_when_no_movement
  alias: Turn off kitchen light 15 minutes after last movement
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_sensor_motion
    to: 'off'
    for: 0:15:00
  condition:
  - condition: time
    after: '19:50:00'
    before: 06:00:00
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.kitchen_pendant_lights
  - service: light.turn_off
    entity_id: light.kitchen_downlight
    
- id: turn_on_off_bedroom_lights_with_click
  alias: Turn on and off bedroom lights with click
  trigger:
    platform: state
    entity_id: sensor.wireless_button_click
    to: 'double'
  action:
    service: light.toggle
    entity_id: light.bedroom_lamps

- id: light_off_at_sunrise
  alias: Turn off lights at sunrise
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.ollie_s_lamp
  - service: light.turn_off
    entity_id: light.teddy_s_lamp
  - service: light.turn_off
    entity_id: light.lounge_room_lamp

- id: light_on_nightlight
  alias: Turn on night light
  initial_state: 'on'
  condition:
  - condition: state
    entity_id: group.household
    state: home
  trigger:
    platform: time
    at: '19:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.night_light

#################################################################
## AC Automations
#################################################################
- alias: hvac-mode-controller-bedroom
  trigger:
    platform: mqtt
    topic: temp/climate/hvac_mode_bedroom
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.payload == ''auto'' }}'
    - condition: template
      value_template: '{{ trigger.payload == ''heat'' }}'
    - condition: template
      value_template: '{{ trigger.payload == ''cool'' }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: /aircon/34ea344df92e/power/set
      payload: 'ON'
  - service: mqtt.publish
    data_template:
      topic: /aircon/34ea344df92e/mode/set
      payload: >
          {% set values = { "auto":"AUTO", "heat":"HEATING", "cool":"COOLING", "off":"OFF" } %}
          {{ values[trigger.payload] if trigger.payload in values.keys() else "off" }}

- alias: hvac-mode-controller-bedroom-power
  trigger:
    platform: mqtt
    topic: temp/climate/hvac_mode_bedroom
    payload: 'off'
  action:
  - service: mqtt.publish
    data_template:
      topic: /aircon/34ea344df92e/power/set
      payload: 'OFF'
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bedroom
      hvac_mode: 'off'

#################################################################
## ZigBee Stuff
#################################################################
- id: zigbee2mqtt_log_level
  alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.zigbee2mqtt_log_level
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
      topic: zigbee2mqtt/bridge/config/log_level
- id: zigbee_join_enabled
  alias: Zigbee Join Enabled
  trigger:
    platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: 'on'
  action:
    service: timer.start
    entity_id: timer.zigbee_permit_join
- id: zigbee_join_disabled
  alias: Zigbee Join Disabled
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  - platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: 'off'
  action:
  - service: timer.cancel
    data:
      entity_id: timer.zigbee_permit_join
  - service: switch.turn_off
    entity_id: switch.zigbee2mqtt_main_join
