#################################################################
## HASS related
#################################################################
- id: hass_start_notification
  alias: NOTIFY (START) Home Assistant
  initial_state: 'on'
  hide_entity: True
  condition:
    - condition: state
      entity_id: input_boolean.options_notifications_push
      state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.mobile_app_pixel4
      data:
        title: ''
        message: 'Home Assistant Started'



          
#################################################################
## Presence
#################################################################
         
- id: notify_resident
  alias: NOTIFY (Location) Resident
  initial_state: 'on'
  hide_entity: True
  condition:
    - condition: state
      entity_id: input_boolean.push_notification
      state: 'on'
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
  trigger:
    - platform: state
      entity_id: person.william
  action:
    - service: notify.mobile_app_pixel4
      data_template:
        message: "{{ trigger.from_state.attributes.friendly_name }} is {% if trigger.to_state.state == 'home' %}at home{% elif trigger.to_state.state == 'not_home' %}away{% else %}at {{ trigger.to_state.state }}{% endif %}."
