default_config:

lovelace:
  mode: yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxies
homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www
    - /config/www/tmp
    - /config/www/deepstack
  auth_mfa_modules:
    - type: totp
# Logger
logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.sensor: fatal
    homeassistant.components.rest.sensor: fatal
    homeassistant.components.command_line.sensor: fatal
    homeassistant.components.braviatv.media_player: fatal
    homeassistant.components.websocket_api: fatal
    homeassistant.components.input_number: fatal
    homeassistant.components.template.sensor: fatal

# Recorder
recorder:
  purge_keep_days: 7

# System Health
system_health:

# influx DB
influxdb:
  host: !secret influx_host

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret base_url
    service_name: google_say

# Tyua Integration
tuya:
  username: !secret tuya_user
  password: !secret tuya_password
  country_code: 61

hacs:
  token: !secret hacs_token
  options:
    experimental: True

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

# Lights
light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.55404001dc4f22ac0486
      - light.55404001dc4f22ac01ca
  - platform: group
    name: Kitchen Lights
    entities:
      - light.80304313dc4f229a3225
      - light.pendant_light_left
      - light.pendant_light_center
      - light.pendant_light_right

# Media Players
media_player:
  - platform: samsungtv_custom
    host: !secret samsungtv_host
    port: 8002
    mac: c0:48:e6:35:1f:40
    sourcelist: '{"TV": "KEY_TV","Switch": "KEY_HDMI1"}'
    applist: "Plex, YouTube"
    protocol: ctl_qled

# Alarm Panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false
    pending_time: 20
    delay_time: 20
    trigger_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

# Notify
notify:
  - name: All_Devices
    platform: group
    services:
      - service: mobile_app_william
      - service: mobile_app_emily
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user

# Zoneminder
zoneminder:
  - host: !secret zm_host
    ssl: true
    verify_ssl: true
    username: !secret zm_username
    password: !secret zm_password

downloader:
  download_dir: /config/www/tmp/

# Camera
camera:
  - platform: local_file
    file_path: /config/www/tmp/zmalert.jpg
    name: Saved Image
  - platform: local_file
    file_path: /config/www/deepstack/deepstack_detector_latest_person.jpg
    name: deepstack_latest_image
  - platform: zoneminder

# Image Processing
image_processing: 
  - platform: facebox
    ip_address: !secret facebox_host
    port: 8087
    scan_interval: 10000
    source: 
      - entity_id: camera.saved_image
  - platform: deepstack_object
    ip_address: !secret deepstack_host
    port: 5000
    api_key: !secret deepstack_key
    #scan_interval: 20 # Optional, in seconds
    save_file_folder: /config/www/deepstack
    save_timestamped_file: True
    target:
      - person
      - car
    source:
      - entity_id: camera.saved_image
        name: deepstack_detector

# Mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Speedtest
speedtestdotnet:
  scan_interval: 60:00
  monitored_conditions:
    - ping
    - download
    - upload

# Input Number
input_number:
  zm_notify_throttle:
    min: 30
    max: 3600
    step: 1
    name: Zoneminder Notification Throttle
    mode: box

# Enable Stream Componenet
stream:
ffmpeg:


sun:

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
