homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  unit_system: metric
  time_zone: Australia/Brisbane
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]

#default_config:
history:
mobile_app:
sun:
system_health:
cast:
ffmpeg:
#stream:

logger:
  default: warning
  logs:
    homeassistant.components.command_line.sensor: error
    homeassistant.components.rest.sensor: error
    homeassistant.components.websocket_api: fatal
    homeassistant.helpers.service: error
    homeassistant.components.media_player: error
    homeassistant.helpers.entity: error

recorder:
  purge_keep_days: 7
  include:
    entities:
      ['person.william', 'person.emily','sensor.speedtest_download', 'sensor.speedtest_upload', 
      'sensor.speedtest_ping', 'sensor.kitchen_sensor_temperature', 'binary_sensor.front_door_motion', 'binary_sensor.front_door',]

hacs:
  token: !secret hacs_token
  options:
    experimental: True

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

tts:
  - platform: google_cloud
    key_file: service_account.json
    voice: en-AU-Wavenet-C
    encoding: linear16

browser_mod:
  devices:
    7a0a300c-b4cf495f:
      name: tablet