#Copy from here#
#Start of dwains-theme necesary code#
homeassistant:
  # If you want to customize entries with friendly_name or custom icon.
  # Read more here: https://www.home-assistant.io/docs/configuration/customizing-devices/
  # Uncomment line below and create file customize.yaml or edit it
  # customize: !include customize.yaml

  # Below is link to packages folder for Dwains Theme
  # Check out user-package-sample in your downloaded folder for an example
  # to create a own package folder
  packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

  # If you had any important strings before in homeassistant: place them back here below
  # 
#End of dwains-theme necesary code#
#Copy till here#




######################################################################
# Below this line is some example code of how the rest of your configuration.yaml file can look like

# # Configure a default setup of Home Assistant (frontend, api, etc)
# default_config:

# # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: https://yourname.duckdns.org


# Some files for automations, groups, scripts and scenes in your root folder
#
# automation: !include_dir_merge_list configuration/automations/ #place every automation in this folder
# group: !include groups.yaml #You really need groups to use my theme :D
# script: !include scripts.yaml
# scene: !include scenes.yaml
