default_config:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - type: module
      url: /hacsfiles/custom-header/custom-header.js
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module   
      url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - type: module
      url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    - type: module
      url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    - type: module
      url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    - type: module
      url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    - type: module
      url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    lovelace-dashboard:
      mode: yaml
      title: Beckett Home
      icon: mdi:house
      show_in_sidebar: true
      filename: ui-lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxies
homeassistant:
  packages: !include_dir_named packages/
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www
    - /config/www/tmp
    - /config/www/deepstack
  auth_mfa_modules:
    - type: totp

# Logbook
logbook:
  exclude:
    entities:
      - automation.ac_bedroomroom_fan_speed_receive
      - automation.ac_bedroomroom_fan_speed_send
      - automation.ac_bedroom_mode_receive
      - automation.ac_bedroom_mode_send
      - automation.ac_bedroom_temp_receive
      - automation.ac_bedroom_temp_send

# Logger
logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.sensor: fatal
    homeassistant.components.rest.sensor: fatal
    homeassistant.components.command_line.sensor: fatal
    homeassistant.components.braviatv.media_player: fatal
    homeassistant.components.websocket_api: fatal
    homeassistant.components.input_number: fatal
    homeassistant.components.template.sensor: fatal

# Recorder
#recorder:
#  purge_keep_days: 7

# System Health
system_health:

# influx DB
influxdb:
  host: !secret influx_host

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret base_url
    service_name: google_say

hacs:
  token: !secret hacs_token
  options:
    experimental: True

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

# Google Assistant
google_assistant:
  project_id: !secret google_assistant_id
  service_account: !include service_account.json
  secure_devices_pin: !secret secure_devices_pin
  report_state: true
  exposed_domains:
    - light
    - scene
    - camera
    - alarm_control_panel
  entity_config:
    media_player.lounge_room_tv:
      name: Lounge Room TV
      room: Lounge Room

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

light:
  - platform: mqtt
    schema: json
    name: kitchen pendant lights
    command_topic: "zigbee2mqtt/kitchen_lights/set"
    state_topic: "zigbee2mqtt/kitchen_lights"
    brightness: true
  - platform: group
    name: Bedroom Lamps
    entities:
      - light.bedroom_lamp_right
      - light.bedroom_lamp_left

# Alarm Panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false
    pending_time: 20
    delay_time: 20
    trigger_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

# Notify
notify:
  - name: All_Devices
    platform: group
    services:
      - service: mobile_app_william
      - service: mobile_app_emily
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user

# Camera
camera:
  - platform: local_file
    file_path: /config/www/tmp/image.jpg
    name: Saved Image
  - platform: local_file
    file_path: /config/www/deepstack/deepstack_detector_latest_person.jpg
    name: deepstack_latest_image
  - platform: ffmpeg
    name: Front Door
    input: !secret front_door_cam_feed
    extra_arguments: '-preset faster -vf "scale=1280:720"'

# Image Processing
image_processing: 
  - platform: facebox
    ip_address: !secret facebox_host
    port: 8087
    scan_interval: 10000
    source: 
      - entity_id: camera.saved_image
  - platform: deepstack_object
    ip_address: !secret deepstack_host
    port: 5000
    api_key: !secret deepstack_key
    save_file_folder: /config/www/deepstack
    save_timestamped_file: True
    target:
      - person
      - car
    source:
      - entity_id: camera.saved_image
        name: deepstack_detector

# Mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Timer
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

# Input text
input_text:
  zigbee2mqtt_old_name:
    name: Zigbee2mqtt Old Name
  zigbee2mqtt_new_name:
    name: Zigbee2mqtt New Name
  zigbee2mqtt_remove:
    name: Zigbee2mqtt Remove

# Climate
climate:
  - platform: mqtt
    name: Bedroom
    modes:
      - "auto"
      - "cool"
      - "heat"
      - "off"
    fan_modes:
      - auto
      - high
      - mid
      - low
    power_command_topic: "/aircon/34ea344df92e/power/set"
    power_state_topic: "/aircon/34ea344df92e/power/value"
    mode_command_topic: "temp/climate/hvac_mode_bedroom"
    mode_state_topic: "/aircon/34ea344df92e/mode/value"
    mode_state_template: >-
      {% set values = { 'AUTO':'auto', 'HEATING':'heat',  'COOLING':'cool', 'OFF':'off' } %}
      {{ values[value] if value in values.keys() else 'OFF' }}
    temperature_command_topic: "/aircon/34ea344df92e/temp/set"
    temperature_state_topic: "/aircon/34ea344df92e/temp/value"
    fan_mode_command_topic: "/aircon/34ea344df92e/fanspeed/set"
    fan_mode_state_topic: "/aircon/34ea344df92e/fanspeed/set"
    min_temp: 16
    max_temp: 32
    temp_step: 0.5
    precision: 0.5

# Browser Mod
browser_mod:

# Device Tracker
device_tracker:
  - platform: nmap_tracker
    hosts: 172.30.1.0/24
    home_interval: 10
    exclude:
      - 172.30.1.1
      - 172.30.1.2
    new_device_defaults:
      track_new_devices: false

# Speedtest
speedtestdotnet:
  scan_interval: 60:00
  monitored_conditions:
    - ping
    - download
    - upload

# Enable Stream Componenet
ffmpeg:

sun:

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
switch: !include switches.yaml
