homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  unit_system: metric
  time_zone: Australia/Brisbane
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]

#default_config:
history:
mobile_app:
sun:
system_health:
cast:
ffmpeg:
stream:

logger:
  default: warning
  logs:
    homeassistant.components.command_line.sensor: error
    homeassistant.components.rest.sensor: error
    homeassistant.components.websocket_api: fatal
    homeassistant.helpers.service: error
    homeassistant.components.media_player: error
    homeassistant.helpers.entity: error

recorder:
  purge_keep_days: 2
  include:
    entities:
      ['person.william', 'person.emily','sensor.speedtest_download', 'sensor.speedtest_upload', 
      'sensor.speedtest_ping', 'sensor.kitchen_sensor_temperature']

person:
  - name: William
    id: william_2
    user_id: 5abb0ba255fc44e78abd65c6527a3c2a
    device_trackers:
      ['device_tracker.william', 'device_tracker.william_ping']

  - name: Emily
    id: emily
    user_id: a6dcbddbf002400a8f64e3c12cb711bc
    device_trackers:
      ['device_tracker.emily', 'device_tracker.emily_ping']

#samsungtv:
#  - host: !secret samsungtv_host

hacs:
  token: !secret hacs_token
  options:
    experimental: True

google_assistant:
  project_id: !secret google_assistant_id
  service_account: !include service_account.json
  secure_devices_pin: !secret secure_devices_pin
  report_state: true
  exposed_domains:
    - light
    - scene
    - camera
    - alarm_control_panel
    - climate
    - media_player
    - input_boolean

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

tts:
  - platform: google_cloud
    key_file: service_account.json
    voice: en-AU-Wavenet-C
    encoding: linear16

browser_mod:
  #devices:
  #  918296e3-e2a54976:
  #    name: imac_chrome
  #  c2080cea-6627150a:
  #    name: tablet