default_config:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - type: module
      url: /hacsfiles/custom-header/custom-header.js
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module   
      url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - type: module
      url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    - type: module
      url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    - type: module
      url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    - type: module
      url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    - type: module
      url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
    - type: module
      url: /hacsfiles/garbage-collection-card/garbage-collection-card.js
    - type: module
      url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
    - type: module
      url: /hacsfiles/lovelace-card-mod/card-mod.js
    - type: css
      url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
  
      
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
    lovelace-dashboard:
      mode: yaml
      title: Beckett Home
      icon: mdi:house
      show_in_sidebar: true
      filename: ui-lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxies
homeassistant:
  packages: !include_dir_named packages/
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www
    - /config/www/tmp
    - /config/www/deepstack
  auth_mfa_modules:
    - type: totp

# Logbook
logbook:
  exclude:
    entities:
      - automation.ac_bedroomroom_fan_speed_receive
      - automation.ac_bedroomroom_fan_speed_send
      - automation.ac_bedroom_mode_receive
      - automation.ac_bedroom_mode_send
      - automation.ac_bedroom_temp_receive
      - automation.ac_bedroom_temp_send

# Logger
logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning
    homeassistant.components.sensor: fatal
    homeassistant.components.rest.sensor: fatal
    homeassistant.components.command_line.sensor: fatal
    homeassistant.components.braviatv.media_player: fatal
    homeassistant.components.websocket_api: fatal
    homeassistant.components.input_number: fatal
    homeassistant.components.template.sensor: fatal

# Recorder
recorder:
  purge_keep_days: 7
  exclude:
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
    event_types:
      - call_service
  include:
    domains:
      - sensor
      - switch
      - media_player
      - input_boolean
      - input_select

# System Health
system_health:

# influx DB
influxdb:
  host: !secret influx_host

# Text to speech
tts:
  #- platform: google_translate
  #  cache: true
  #  cache_dir: /tmp/tts
  #  time_memory: 300
  #  base_url: !secret base_url
  #  service_name: google_say
  - platform: google_cloud
    key_file: service_account.json
    language: en-AU
    gender: female
    voice: en-AU-Wavenet-C
    encoding: mp3
    profiles:
      - handset-class-application
      - medium-bluetooth-speaker-class-device

hacs:
  token: !secret hacs_token
  options:
    experimental: True

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

# Google Assistant
google_assistant:
  project_id: !secret google_assistant_id
  service_account: !include service_account.json
  secure_devices_pin: !secret secure_devices_pin
  report_state: true
  exposed_domains:
    - light
    - scene
    - camera
    - alarm_control_panel
    - climate
    - media_player
  #entity_config:
  #  media_player.lounge_room_tv:
  #    name: Lounge Room TV
  #    room: Lounge Room

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

light:
  - platform: mqtt
    schema: json
    name: kitchen pendant lights
    command_topic: "zigbee2mqtt/kitchen_lights/set"
    state_topic: "zigbee2mqtt/kitchen_lights"
    brightness: true
    color_temp: true
    rgb: true
  - platform: group
    name: Bedroom Lamps
    entities:
      - light.bedroom_lamp_right
      - light.bedroom_lamp_left
  - platform: group
    name: kitchen_lights
    entities:
      - light.kitchen_pendant_lights
      - light.kitchen_downlight

# Inputs
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_text: !include includes/input_text.yaml

# Logging and History
device_tracker: !include includes/device_trackers.yaml

# Managed via UI
scene: !include scenes.yaml
script: !include scripts.yaml
  
# Others
ffmpeg:
stream:
sun:
automation: !include_dir_merge_list automation
alarm_control_panel: !include includes/alarm_panel.yaml
notify: !include includes/notify.yaml
image_processing: !include includes/image_processing.yaml
mqtt: !include includes/mqtt.yaml
camera: !include includes/cameras.yaml
climate: !include includes/climate.yaml
group: !include includes/groups.yaml
#automation old: !include automations_old.yaml
zone: !include includes/zones.yaml
sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensor.yaml
speedtestdotnet: !include includes/speedtestdotnet.yaml
switch: !include includes/switches.yaml
timer: !include includes/timer.yaml
