
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 2
homeassistant:
  whitelist_external_dirs:
    - /config/www
    - /config/www/facebox

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret base_url
    service_name: google_say

# Tyua Integration
tuya:
  username: !secret tuya_user
  password: !secret tuya_password
  country_code: 61

hacs:
  token: !secret hacs_token
  python_script: True
  theme: True
  options:
    experimental: True

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

# Hue integration
hue:
  bridges:
    - host: !secret hue_host
      allow_hue_groups: true

# Lights
light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.55404001dc4f22ac0486
      - light.55404001dc4f22ac01ca
  - platform: group
    name: Kitchen Lights
    entities:
      - light.80304313dc4f229a3225
      - light.pendant_light_left
      - light.pendant_light_center
      - light.pendant_light_right

# Media Players
media_player:
  - platform: samsungtv_custom
    host: !secret samsungtv_host
    port: 8002
    mac: c0:48:e6:35:1f:40
    sourcelist: '{"TV": "KEY_TV","Switch": "KEY_HDMI1"}'
    applist: "Plex, YouTube"
    protocol: ctl_qled

# Alarm Panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    code_arm_required: false
    pending_time: 20
    delay_time: 20
    trigger_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

# Image Processing
image_processing: 
  - platform: facebox
    ip_address: !secret facebox_host
    port: 8086
    scan_interval: 10000
    source: 
      - entity_id: camera.local_file
        name: face_counter
  - platform: deepstack_object
    ip_address: !secret deepstack_host
    port: 5000
    api_key: !secret deepstack_key
    # scan_interval: 30 # Optional, in seconds
    save_file_folder: /config/www/deepstack
    save_timestamped_file: True
    source:
      - entity_id: camera.local_file
        name: deepstack_person_detector

# Notify
notify:
  - name: All_Devices
    platform: group
    services:
      - service: mobile_app_william
      - service: mobile_app_emily

# Camera
camera:
  - platform: local_file
    file_path: /config/www/images/family.png
  - platform: local_file
    file_path: /config/www/deepstack/deepstack_person_detector_latest_person.jpg
    name: deepstack_latest_person

# Enable Stream Componenet
stream:

# Input Booleans
input_boolean:
  push_notification:
    name: Notify when someone arrives home
    initial: on
    icon: mdi:bell

sun:

# Includes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
customize: !include customize.yaml
