#-------------------------------------------
# Light Groups
# @Backslashh
# Original Repo : https://github.com/backslashh/homeassistant-config
#-------------------------------------------

- platform: mqtt
  schema: json
  name: kitchen pendant lights
  command_topic: "zigbee2mqtt/kitchen_lights/set"
  state_topic: "zigbee2mqtt/kitchen_lights"
  brightness: true
  color_temp: true
  rgb: true

- platform: group
  name: Bedroom Lamps
  entities:
  - light.bedroom_lamp_right
  - light.bedroom_lamp_left

- platform: group
  name: Kitchen Lights
  entities:
  - light.kitchen_pendant_lights
  - light.kitchen_downlight

- platform: group
  name: Teddys Room
  entities:
    - light.teddy_s_lamp
 
- platform: group
  name: Ollies Room
  entities:
    - light.ollie_s_lamp

- platform: group
  name: Lounge Room Lights
  entities:
    - light.lounge_room_lamp