##########################################################################
#                                                                        #
#                              * SETTINGS *                              #
#                                                                        #
##########################################################################

custom_header:
    exceptions:
      - conditions:
          query_string: kiosk
        config:
          kiosk_mode: false



##########################################################################
#                                                                        #
#                              * LOVELACE *                              #
#                                                                        #
##########################################################################

title: Home
views:
  - panel: true
    path: default_view
    cards:
      - type: horizontal-stack
        title:
        cards:
          - type: vertical-stack
            cards:
              - type: markdown
                content: >
                  # {{ states('sensor.time') }}

                  ## {{ states('sensor.sidebar_day') }}, {{ states('sensor.sidebar_date') }}

                  {{ states('sensor.sidebar_greeting') }} {{ states('sensor.sidebar_weather') }} 

                  {{ states('sensor.sidebar_active') }}
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
          - type: vertical-stack
            cards:
              - type: weather-forecast
                entity: weather.home
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
          - type: vertical-stack
            cards:
              - type: entities
                entities:
                  - entity: person.william
                    name: William
                  - entity: person.emily
                    name: Emily
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
                
