##########################################################################
#                                                                        #
#                              * SETTINGS *                              #
#                                                                        #
##########################################################################

custom_header:
    exceptions:
      - conditions:
          query_string: kiosk
        config:
          kiosk_mode: false

decluttering_templates: !include_dir_merge_named lovelace/decluttering_templates          

button_card_templates:
  header:
    styles:
      card:
        - box-shadow: none
        - border-radius: 0%
        - padding: 0%
        - font-size: 10px
        - text-shadow: 0px 0px 0px black
        - text-transform: capitalize
      icon:
        - width: 15%
        - margin-top: 0%
        - margin-left: 0%
      name:
        - font-size: 16px
        - text-transform: capitalize
        - justify-self: start
        - margin-left: 1%
  standard_button:
    styles:
      card:
        - font-size: 10px
      icon:
        - width: 30%
      name:
        - font-size: 12px
      state:
        - justify-self: start
        - font-size: 10px
        - padding: 0px 5px



##########################################################################
#                                                                        #
#                              * LOVELACE *                              #
#                                                                        #
##########################################################################

title: Home
views:
  - panel: true
    path: default_view
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title:
            cards:
              - type: markdown
                content: >
                  # {{ states('sensor.time') }}

                  ## {{ states('sensor.sidebar_day') }}, {{ states('sensor.sidebar_date') }}

                  {{ states('sensor.sidebar_greeting') }} {{ states('sensor.sidebar_weather') }} 

                  {{ states('sensor.sidebar_active') }}
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 50px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
              - type: horizontal-stack
                cards:
                  - type: weather-forecast
                    entity: weather.home
                    style:
                      .: |
                        ha-card {
                          --ha-card-background: none !important;
                          box-shadow: none !important;
                        }
          - type: horizontal-stack
            cards:
              - type: markdown
                content: |
                  # Home
                style:
                  .: |
                    ha-card {
                      --ha-card-background: none !important;
                      box-shadow: none !important;
                    }
                  ha-markdown:
                    $: |
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
          - type: horizontal-stack
            cards:            
              - type: custom:decluttering-card
                template: "simple_link"
                variables:
                  - path: kitchen
                  - name: Kitchen
                  - icon: mdi:chef-hat
                  - entity: light.kitchen_lights
              - type: custom:decluttering-card
                template: "simple_link"
                variables:
                  - path: loungeroom
                  - name: Lounge Room
                  - icon: mdi:sofa
                  - entity: light.lounge_room_lamp
              - type: custom:decluttering-card
                template: "simple_link"
                variables:
                  - path: bedroom
                  - name: Bedroom
                  - icon: mdi:heart-outline
                  - entity: light.bedroom_lamps
              - type: custom:decluttering-card
                template: "simple_link"
                variables:
                  - path: ollie_room
                  - name: Ollie's Room
                  - icon: mdi:paw
                  - entity: light.ollie_s_lamp
              - type: custom:decluttering-card
                template: "simple_link"
                variables:
                  - path: teddy_room
                  - name: Teddy's Room
                  - icon: mdi:pokeball
                  - entity: light.teddy_s_lamp

            
                
