resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module

title: Beckett Home
views:
  - icon: mdi:home-assistant
    id: home
    # Name of the view. Will be used as the tooltip for tab icon
    title: Home
    # theme: darkorange
    badges:
      - person.william
      - person.emily
      - binary_sensor.kitchen_sensor_motion
      - binary_sensor.front_door_motion
    cards:
      - type: entities
        name: Doors
        entities:
          - binary_sensor.garage_door
          - binary_sensor.back_door
      - type: alarm-panel
        name: House Alarm
        entity: alarm_control_panel.home_alarm
        states:
          - arm_home
          - arm_away
      - type: entities
        title: Lights
        entities:
          - entity: light.34856070bcddc23658e4
            type: custom:slider-entity-row
            toggle: true
          - entity: light.55404001dc4f22ac01ca
            type: custom:slider-entity-row
            toggle: true
          - entity: light.55404001dc4f22ac0486
            type: custom:slider-entity-row
            toggle: true
          - entity: light.80304313dc4f229a3225
            type: custom:slider-entity-row
            toggle: true
          - entity: light.pendant_light_left
            type: custom:slider-entity-row
            toggle: true
          - entity: light.pendant_light_center
            type: custom:slider-entity-row
            toggle: true
          - entity: light.pendant_light_right
            type: custom:slider-entity-row
            toggle: true
          - entity: light.ollie_s_lamp
            type: custom:slider-entity-row
            toggle: true
          - entity: light.teddy_s_lamp
            type: custom:slider-entity-row
            toggle: true

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: custom:weather-card
        entity: weather.dark_sky
      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - sensor.dark_sky_summary
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_daily_summary
  
  - icon: mdi:cctv
    id: cameras
    cards:
      - type: picture-glance
        title: Front Door
        camera_image: camera.front_door
        camera_view: live
        entities:
         - camera.front_door
      - type: picture-entity
        entity: camera.front_door_image
      #- type: picture-entity
      #  entity: camera.saved_image
      - type: picture-entity
        entity: camera.deepstack_latest_person
      - type: picture-entity
        entity: camera.deepstack_latest_car
      - type: entities
        entities:
          - image_processing.facebox_front_door
          - image_processing.facebox_saved_image
          - image_processing.deepstack_person_detector
        #  - image_processing.deepstack_car_detector
          - sensor.front_door_detection

  - icon: mdi:play-circle-outline
    id: media
    title: Media
    badges:
      - sensor.plex_bms01
    cards:
      - type: custom:mini-media-player
        entity: media_player.all_speakers
        artwork: cover
        hide:
          source: true
          power_state: true
      - type: custom:mini-media-player
        entity: media_player.kitchen_display
      - type: custom:mini-media-player
        entity: media_player.lounge_room_speaker
      - type: custom:mini-media-player
        entity: media_player.bedroom_speaker
      - type: custom:mini-media-player
        entity: media_player.teddy_s_speaker
      - type: custom:mini-media-player
        entity: media_player.ollie_s_speaker
      - type: entities
        entities:
          - type: custom:mini-media-player
            entity: media_player.all_speakers
            group: true
            source: icon
            info: short
            hide:
              volume: true
              power: true
          - type: custom:mini-media-player
            entity: media_player.kitchen_display
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.ollie_s_speaker
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.teddy_s_speaker
            group: true
            hide:
              controls: true
          - type: custom:mini-media-player
            entity: media_player.lounge_room_speaker
            group: true
            hide:
              controls: true
      - type: horizontal-stack
        cards:
          - entity: media_player.bedroom_tv
            type: custom:mini-media-player
            info: short
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
          - entity: media_player.samsung_tv_remote
            type: custom:mini-media-player
            info: scroll
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false
      - type: horizontal-stack
        cards:
          - entity: media_player.plex_tv_ua55mu7000
            type: custom:mini-media-player
            info: scroll
            artwork: cover

  - icon: mdi:settings
    id: settings
    title: Settings
    cards:
      - type: entities
        title: Switches
        show_header_toggle: true
        entities:
          - input_boolean.options_notifications_push
