button_card_templates:
  header:
    styles:
      card:
        - box-shadow: none
        - border-radius: 0%
        - padding: 0%
        - font-size: 10px
        - text-shadow: 0px 0px 0px black
        - text-transform: capitalize
      icon:
        - width: 15%
        - margin-top: 0%
        - margin-left: 0%
      name:
        - font-size: 16px
        - text-transform: capitalize
        - justify-self: start
        - margin-left: 1%
  standard_button:
    styles:
      card:
        - font-size: 10px
      icon:
        - width: 30%
      name:
        - font-size: 12px
      state:
        - justify-self: start
        - font-size: 10px
        - padding: 0px 5px
  soft_button:
    show_icon: true
    show_name: false
    state:
      - styles:
          icon:
            - color: 'var(--paper-item-icon-active-color)  '
        value: 'on'
    style: |
      ha-card {
        margin: 10px;
        box-shadow: 
          {% if is_state('sun.sun', 'above_horizon') and is_state('light.ollie_s_lamp', 'on') %}
            inset -4px -4px 8px 0 rgba(255,255,255,.5), inset 4px 4px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'above_horizon') and is_state('light.ollie_s_lamp', 'off') %}                      
            -5px -5px 8px 0 rgba(255,255,255,.5),5px 5px 8px 0 rgba(0,0,0,.03);
          {% elif is_state('sun.sun', 'below_horizon') and is_state('light.ollie_s_lamp', 'on') %}                      
            inset -4px -4px 10px 0 rgba(50, 50, 50,.5), inset 4px 4px 12px 0 rgba(0,0,0,.3); 
          {% elif is_state('sun.sun', 'below_horizon') and is_state('light.ollie_s_lamp', 'off') %}   
            -5px -5px 8px 0 rgba(50, 50, 50,.5),5px 5px 8px 0 rgba(0,0,0,.15);
          {% endif %}    
      }
    styles:
      card:
        - width: 80px
        - height: 80px
        - border-radius: 15px
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)

custom_header:
  compact_mode: true
  footer_mode: true
  elements_color: var(--primary-text-color)
  tab_indicator_color: var(--state-icon-active-color)
  background: var(--primary-background-color)
  #background: var(--app-header-background-color)
  #elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  #tab_indicator_color: var(--state-icon-active-color)
  
title: Beckett Home
views:
  !include_dir_merge_list lovelace/views/
decluttering_templates: !include_dir_merge_named lovelace/decluttering_templates

