resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module

custom_header:
  compact_mode: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)

title: Beckett Home
views:
  - icon: mdi:home-assistant
    id: home
    title: Home
    badges:
      - person.william
      - person.emily
      - binary_sensor.kitchen_sensor_motion
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            name: Doors
            entities:
              - binary_sensor.garage_door
              - binary_sensor.back_door
          - type: custom:mini-graph-card
          entities:
            - entity: binary_sensor.kitchen_sensor_motion
            - entity: binary_sensor.garage_door
            - entity: binary_sensor.back_door
          name: Motion & Doors
          hours_to_show: 24
          points_per_hour: 60
          aggregate_func: max
          line_width: 2
          height: 20
          state_map:
            - value: "off"
              label: Clear
            - value: "on"
              label: Alert
      - type: vertical-stack
        cards:
          - type: alarm-panel
            name: House Alarm
            entity: alarm_control_panel.home_alarm
            states:
              - arm_home
              - arm_away
      - type: vertical-stack
        cards:
          - type: entities
            title: Lights
            entities:
              - entity: light.34856070bcddc23658e4
                type: custom:slider-entity-row
                toggle: true
              - entity: light.bedroom_lights
                type: custom:slider-entity-row
                toggle: true
                #- entity: light.55404001dc4f22ac01ca
              #  type: custom:slider-entity-row
              #  toggle: true
              #- entity: light.55404001dc4f22ac0486
              #  type: custom:slider-entity-row
              #  toggle: true
              - entity: group.kitchen_lights
                type: custom:slider-entity-row
                toggle: true
              #- entity: light.80304313dc4f229a3225
              #  type: custom:slider-entity-row
              #  toggle: true
              #- entity: light.pendant_light_left
              #  type: custom:slider-entity-row
              #  toggle: true
              #- entity: light.pendant_light_center
              #  type: custom:slider-entity-row
              #  toggle: true
              #- entity: light.pendant_light_right
              #  type: custom:slider-entity-row
              #  toggle: true
              - entity: light.ollie_s_lamp
                type: custom:slider-entity-row
                toggle: true
              - entity: light.teddy_s_lamp
                type: custom:slider-entity-row
                toggle: true

  - icon: mdi:weather-cloudy
    id: weather
    title: Weather
    cards:
      - type: vertical-stack
        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
          - type: entities
            title: Weather
            show_header_toggle: false
            entities:
              - sensor.dark_sky_summary
              - sensor.dark_sky_hourly_summary
              - sensor.dark_sky_daily_summary
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.kitchen_sensor_temperature
                name: Kitchen
                show_state: true
                state_adaptive_color: true
              - entity: sensor.dark_sky_temperature
                name: Outside
                show_state: false
                state_adaptive_color: true
                show_fill: false
            name: Temperature
            hours_to_show: 24
            points_per_hour: 20
            line_width: 2
            hour24: true
            height: 180
  
  - icon: mdi:cctv
    id: cameras
    cards:
      - type: picture-glance
        title: Front Door
        camera_image: camera.front_door
        camera_view: live
        entities:
         - camera.front_door
      - type: picture-entity
        entity: camera.deepstack_latest_person
      - type: picture-entity
        entity: camera.deepstack_latest_car
      - type: entities
        entities:
          - image_processing.facebox_front_door
          - image_processing.deepstack_person_detector
          - image_processing.deepstack_car_detector
          - sensor.front_door_detection

  - icon: mdi:play-circle-outline
    id: media
    title: Media
    badges:
      - sensor.plex_bms01
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.kitchen_display
            icon: mdi:google
            artwork: cover
            info: scroll
          - type: custom:mini-media-player
            entity: media_player.lounge_room_speaker
            icon: mdi:google
            artwork: cover
            info: scroll
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            icon: mdi:google
            artwork: cover
            info: scroll
          - type: custom:mini-media-player
            entity: media_player.teddy_s_speaker
            icon: mdi:google
            artwork: cover
            info: scroll
          - type: custom:mini-media-player
            entity: media_player.ollie_s_speaker
            icon: mdi:google
            artwork: cover
            info: scroll
      - type: horizontal-stack
        cards:
          - entity: media_player.samsung_tv_remote
            type: custom:mini-media-player
            info: scroll
            artwork: cover
            hide:
              mute: true
              icon: true
              power_state: false

  - icon: mdi:settings
    id: settings
    title: Settings
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Switches
            show_header_toggle: true
            entities:
              - input_boolean.options_notifications_push
          - type: entities
            title: Zoneminder Latest Alert
            show_header_toggle: false
            entities:
              - sensor.front_door_alerts
          - type: entities
            title: Fail2Ban
            show_header_toggle: false
            entities:
              - sensor.fail2ban_hass_iptables
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - speedtestdotnet.ping
              name: Ping
              hours_to_show: 24
              points_per_hour: 20
              line_width: 2
              hour24: true
              height: 180
          - type: custom:mini-graph-card
            entities:
              - speedtestdotnet.download
              name: Download
              hours_to_show: 24
              points_per_hour: 20
              line_width: 2
              hour24: true
              height: 180
          - type: custom:mini-graph-card
            entities:
              - speedtestdotnet.upload
              name: Upload
              hours_to_show: 24
              points_per_hour: 20
              line_width: 2
              hour24: true
              height: 180
