# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/house_information.html

house_information:
  favorites:
    - entity: binary_sensor.garage_door
      icon_on: mdi:garage-open-variant
      icon_off: mdi:garage-variant 
    - entity: binary_sensor.back_door
      icon_on: fas:door-open
      icon_off: fas:door-closed
    - entity: binary_sensor.kitchen_sensor_motion
      icon_on: mdi:motion-binary_sensor
      icon_off: mdi:walk
    - entity: binary_sensor.front_door_motion
      icon_on: mdi:motion-binary_sensor
      icon_off: mdi:walk
    - entity: input_boolean.guest_mode
    - entity: input_boolean.morning_meds_taken
      icon_on: mdi:check-circle
      icon_off: mdi:check-circle-outline
    - entity: input_boolean.evening_meds_taken
      icon_on: mdi:check-circle
      icon_off: mdi:check-circle-outline
    - entity: input_boolean.bedtime_meds_taken
      icon_on: mdi:check-circle
      icon_off: mdi:check-circle-outline

  calendar:
    - calendar.trash
    - calendar.birthdays