# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

more_page:
  addons:
    - name: AC Units
      icon: mdi:air-conditioner
      path: 'dwains-theme/addons/more_page/ac/page.yaml'
#       data:
#         some_data: 'This is some data parsed.'
#         some_other_data: 'and some other data.'