# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

more_page:
  addons:
    - name: Media
      icon: mdi:play-circle-outline
      path: 'dwains-theme/addons/more_page/media/page.yaml'
    - name: AC Units
      icon: mdi:air-conditioner
      path: 'dwains-theme/addons/more_page/ac/page.yaml'
    - name: Zigbee2MQTT
      icon: mdi:zigbee
      path: 'dwains-theme/addons/more_page/zigbee2mqtt/page.yaml'
    - name: Zigbee Map
      icon: mdi:map
      path: 'dwains-theme/addons/more_page/zigbeeMap/page.yaml'
    - name: Coronavirus
      icon: mdi:hospital-box-outline
      path: 'dwains-theme/addons/more_page/coronavirus/page.yaml'