# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/persons.html

persons: 
  - name: William
    track: person.william
    picture_path: 'images/persons/william.png'
  - name: Emily
    track: person.emily
    picture_path: 'images/persons/emily.png'