# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Bedroom
    icon: fas:bed
    light: group.bedroom_lights
    climate: climate.bedroom
    media_player: group.bedroom_media_players
  - name: Kitchen
    icon: fas:utensils
    light: group.kitchen_lights
    temperature: sensor.kitchen_sensor_temperature
    motion: binary_sensor.kitchen_sensor_motion
    door: binary_sensor.back_door
    media_player: media_player.kitchen_display
  - name: Ollie's Room
    icon: fas:heart
    light: group.ollie_lights
    media_player: media_player.ollie_s_speaker
  - name: Teddy's Room
    icon: mdi:pokeball
    light: group.teddy_lights
    media_player: media_player.teddy_s_speaker
  - name: Lounge Room
    icon: fas:couch
    light: group.lounge_room_lights
    media_player: media_player.lounge_room_tv
  - name: Front Room
    icon: fas:puzzle-piece
    media_player: media_player.front_room_speaker
  - name: Garage
    icon: mdi:garage-variant
    door: binary_sensor.garage_door