# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Front Door
    icon: fas:key
    motion: binary_sensor.front_door_motion
  - name: Bedroom
    icon: fas:bed
    light: group.bedroom_lights
    media_player: group.bedroom_media_players
  - name: Kitchen
    icon: fas:utensils
    light: group.kitchen_lights
    temperature: sensor.kitchen_sensor_temperature
    motion: sensor.kitchen_sensor_motion
    door: binary_sensor.back_door
    media_player: media_player.kitchen_display
  - name: Ollie Room
    icon: fas:paw
    light: group.ollie_lights
    media_player: media_player.ollie_s_speaker
  - name: Teddy Room
    icon: fas:fort-awesome
    light: group.teddy_lights
    media_player: media_player.teddy_s_speaker
  - name: Lounge Room
    icon: fas:couch
    light: group.lounge_room_lights
    media_player: group.lounge_room_media_players
  - name: Garage
    icon: fas:garage
    door: binary_sensor.garage_door