  - icon: mdi:cog
    id: settings
    title: Settings
    path: settings
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              # Network
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown:
                $: |
                  h1 {
                    font-size: 20px;
                    font-weight: bold;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
          - type: entities
            show_header_toggle: false
            entities:
              - sensor.wifi_status
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px;   
              }
          - type: custom:mini-graph-card
            name: Download/Upload
            entities:
              - entity: sensor.speedtest_download
                name: Download
                show_state: true
                state_adaptive_color: true
              - entity: sensor.speedtest_upload
                name: Upload
                show_state: true
                state_adaptive_color: true
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px;  
              }
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              # Sensors
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown:
                $: |
                  h1 {
                    font-size: 20px;
                    font-weight: bold;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
          - type: entities
            show_header_toggle: false
            entities:
              - binary_sensor.kitchen_sensor_motion
              - binary_sensor.bedroom_motion
              - binary_sensor.front_door
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px;  
              }
      - type: vertical-stack
        cards:
          - type: markdown
            content: |
              # Switches
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown:
                $: |
                  h1 {
                    font-size: 20px;
                    font-weight: bold;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.alert_mode
              - input_boolean.text_notifications
              - input_boolean.meds_reminder
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px; 
              }