#-------------------------------------------
# Template Sensors
# @Backslashh
# Original Repo : https://github.com/backslashh/homeassistant-config
#-------------------------------------------

- platform: template
  sensors:
  #front_door_detection:
  #  friendly_name: 'Front Door Detection'
  #  value_template: '{{ states.image_processing.facebox_saved_image.attributes.faces[0]["name"]|title()}}'
  lights_on:
    value_template: >
      {% set lights = [
        states.light.bedroom_lamps,
        states.light.kitchen_lights,
        states.light.lounge_room_lamp,
        states.light.ollie_s_lamp,
        states.light.teddy_s_lamp,
        ] %}
      {{ lights | selectattr('state','eq','on') | list | count }}