- id: '1592804710966'
  alias: turn on lights at sunset
  description: ''
  trigger:
  - event: sunset
    offset: -02:00:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - scene: scene.bright_lights
  - scene: scene.bedroom_lamps_bright
  - brightness: 255
    device_id: 13c7e8ef3a73444484d1ba5f6076b425
    domain: light
    entity_id: light.lounge_room_lamp
    type: turn_on
- id: '1592804786192'
  alias: Turn off lights at bed time
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - device_id: 13c7e8ef3a73444484d1ba5f6076b425
    domain: light
    entity_id: light.lounge_room_lamp
    type: turn_off
- id: '1592804840487'
  alias: Turn on night lights
  description: ''
  trigger:
  - at: '19:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - scene: scene.night_light
- id: '1592804907305'
  alias: Turn off lamps at sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: fea9c6efb2e4493c90ddd26ad0789137
    domain: light
    entity_id: light.teddy_s_lamp
    type: turn_off
  - device_id: 32e10d16f2894e6584d045b8040ba7ea
    domain: light
    entity_id: light.ollie_s_lamp
    type: turn_off

- id: '1593405189369'
  alias: Activate Birght Lights when coming home after sunset
  description: ''
  trigger:
  - entity_id: group.family
    platform: state
    to: home
  condition:
  - condition: device
    device_id: 32e10d16f2894e6584d045b8040ba7ea
    domain: light
    entity_id: light.ollie_s_lamp
    type: is_off
  - condition: device
    device_id: fea9c6efb2e4493c90ddd26ad0789137
    domain: light
    entity_id: light.teddy_s_lamp
    type: is_off
  - after: sunset
    condition: sun
  action:
  - data: {}
    entity_id: scene.bright_lights
    service: scene.turn_on
- id: '1593405295014'
  alias: Activate Guest mode when Guest is here
  description: ''
  trigger:
  - entity_id: group.guests
    platform: state
    to: home
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.guest_mode
    service: input_boolean.turn_on
- id: '1593405367977'
  alias: Turn Off Guest mode when guests leave
  description: ''
  trigger:
  - entity_id: group.guests
    for: 00:03:00
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.guest_mode
    service: input_boolean.turn_off
