---
#- from github.com/wjbeckett/homeassistant-config
- platform: manual
  name: Home Alarm
  code: !secret alarm_code
  code_arm_required: false
  arming_time: 20
  delay_time: 20
  trigger_time: 30
  disarmed:
    trigger_time: 0
  armed_home:
    arming_time: 0
    delay_time: 0