---
#- from github.com/wjbeckett/homeassistant-config
- platform: wyzesense
  device: "/dev/hidraw0"
- platform: mqtt
  state_topic: "home/frontdoor/camera/motion"
  name: Front Door Motion
  device_class: motion
- platform: template
  sensors:
    morning_meds_taken:
      friendly_name: Morning Meds Taken
      entity_id: input_boolean.morning_meds_taken
      value_template: >-
        {% if is_state('input_boolean.morning_meds_taken', 'on') %}
          Yes
        {% else %}
          No
        {% endif %}
    evening_meds_taken:
      friendly_name: Evening Meds Taken
      entity_id: input_boolean.evening_meds_taken
      value_template: >-
        {% if is_state('input_boolean.evening_meds_taken', 'on') %}
          Yes
        {% else %}
          No
        {% endif %}
    bedtime_meds_taken:
      friendly_name: Bedtime Meds Taken
      entity_id: input_boolean.bedtime_meds_taken
      value_template: >-
        {% if is_state('input_boolean.bedtime_meds_taken', 'on') %}
          Yes
        {% else %}
          No
        {% endif %}

- platform: bayesian
  prior: 0.5
  name: 'William Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.william_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.william'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Emily Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.emily_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.emily'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'