---
#- from github.com/wjbeckett/homeassistant-config
- platform: wyzesense
  device: "/dev/hidraw0"
#- platform: mqtt
#  state_topic: "home/frontdoor/camera/motion"
#  name: Front Door Motion
#  device_class: motion
- platform: mqtt
  name: "Front Door Motion"
  state_topic: "home/frontdoor/camera/motion"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion