---
#- from github.com/wjbeckett/homeassistant-config
#- platform: facebox
#  ip_address: !secret facebox_host
#  port: 8087
#  scan_interval: 10000
#  source: 
#    - entity_id: camera.saved_image
- platform: deepstack_object
  ip_address: !secret deepstack_host
  port: 5000
  api_key: !secret deepstack_key
  save_file_folder: /config/www/deepstack
  save_timestamped_file: True
  targets:
    - person
    - car
  source:
    - entity_id: camera.saved_image
      name: deepstack_detector
- platform: openalpr_cloud
  api_key: !secret openalpr
  region: au
  source:
    - entity_id: camera.alpr_test