#-------------------------------------------
# Bedroom Related Packages
# @Backslashh
# Original Repo : https://github.com/backslashh/homeassistant-config
#-------------------------------------------

automation:
  - id: '1592805027019'
    alias: Toggle Bedroom lamps with a single click
    description: ''
    trigger:
    - platform: deconz_event
      event: 1002
      id: wireless_button
    #- platform: state
    #  entity_id: sensor.wireless_button_click
    #  to: 'single'
    condition: []
    action:
    - data: {}
      entity_id: light.bedroom_lamps
      service: light.toggle

  - id: '1592805067463'
    alias: Activate Bedroom Bright with double click
    description: ''
    trigger:
    - platform: deconz_event
      event: 1004
      id: wireless_button
    #- platform: state
    #  entity_id: sensor.wireless_button_click
    #  to: 'double'
    condition: []
    action:
    - data:
        transition: 2.5
      entity_id: scene.bedroom_lamps_bright
      service: scene.turn_on

  - id: '1592805105771'
    alias: Activate Bedroom Night Light with long press
    description: ''
    trigger:
    - platform: deconz_event
      event: 1001
      id: wireless_button
    #- platform: state
    #  entity_id: sensor.wireless_button_click
    #  to: 'long'
    condition: []
    action:
    - data:
        transition: 2.5
      entity_id: scene.bedroom_night_light
      service: scene.turn_on

  - id: '1592805608239'
    alias: turn on Bedroom lamps when motion is detected
    description: ''
    trigger:
    - entity_id: binary_sensor.bedroom_motion
      platform: state
      to: 'on'
    condition:
    - after: 07:30:00
      before: '20:00:00'
      condition: time
    - condition: not
      conditions:
      - condition: device
        device_id: 154ca135cbd14827a3fdc722d10060f4
        domain: media_player
        entity_id: media_player.bedroom_tv
        type: is_playing
    - condition: state
      entity_id: light.bedroom_lamps
      state: 'off'
    action:
    - data:
        transition: 2.5
      entity_id: scene.bedroom_lamps_bright
      service: scene.turn_on

  - id: '1592805733176'
    alias: Turn off bedroom lamps when no motion is detected
    description: ''
    trigger:
    - entity_id: binary_sensor.bedroom_motion
      for: 00:03:00
      platform: state
      to: 'off'
    condition:
    - condition: not
      conditions:
      - condition: device
        device_id: 154ca135cbd14827a3fdc722d10060f4
        domain: media_player
        entity_id: media_player.bedroom_tv
        type: is_playing
    - before: '20:00:00'
      condition: time
    action:
    - data:
        transition: 2.5
      entity_id: light.bedroom_lamps
      service: light.turn_off
      
  - id: '1592805822114'
    alias: Dim the bedroom lamps when the tv is playing
    description: ''
    trigger:
    - entity_id: media_player.bedroom_tv
      platform: state
      to: playing
    condition:
    - condition: state
      entity_id: light.bedroom_lamps
      state: 'on'
    action:
    - data:
        transition: 2.5
      entity_id: scene.bedroom_night_light
      service: scene.turn_on

  - alias: Turn off the bedroom lamps when we are going to sleep
    trigger:
    - platform: state
      entity_id:
        - sensor.william_pixel_battery_state
      to: "discharging"
    condition:
    - condition: template
      value_template: "{{ states.sensor.emily_battery_state.state != 'discharging' }}"
    - condition: state
      entity_id: media_player.bedroom_tv
      state: 'playing'
    - condition: sun
      after: sunset
    action:
    - service: light.turn_off
      entity_id: light.bedroom_lamps

