---
#- from github.com/wjbeckett/homeassistant-config
camera:
  - platform: local_file
    file_path: /config/www/tmp/image.jpg
    name: Saved Image
  - platform: local_file
    file_path: /config/www/deepstack/deepstack_detector_latest.jpg
    name: deepstack_latest_image
  - platform: generic
    name: wyze
    still_image_url: !secret wyze_image
    stream_source: !secret wyze_stream
    authentication: basic
  - platform: reolink_dev
    host: !secret front_door_cam_IP
    username: !secret front_door_cam_user
    password: !secret front_door_cam_password
    name: Front Door
    stream: main
    protocol: rtmp
    scan_interval: 5

binary_sensor:
  platform: template
  sensors:
    front_door_motion:
      friendly_name: Front Door
      device_class: motion
      entity_id: camera.front_door
      value_template: "{{ is_state('camera.front_door', 'motion') }}"
      delay_off: 
          seconds: 30

switch:
  - platform: template
    switches:          
      camera_front_door_ir_lights:
        value_template: "{{ is_state_attr('camera.front_door', 'ir_lights_enabled', true) }}"
        turn_on:
          service: camera.enable_ir_lights
          data:
            entity_id: camera.front_door
        turn_off:
          service: camera.disable_ir_lights
          data:
            entity_id: camera.front_door
        icon_template: >-
          {% if is_state_attr('camera.front_door', 'ir_lights_enabled', true) %}
            mdi:flashlight
          {% else %}
            mdi:flashlight-off
          {% endif %}

      camera_front_door_motion_detection:
        value_template: "{{ is_state_attr('camera.front_door', 'motion_detection_enabled', true) }}"
        turn_on:
          service: camera.enable_motion_detection
          data:
            entity_id: camera.front_door
        turn_off:
          service: camera.disable_motion_detection
          data:
            entity_id: camera.front_door
        icon_template: >-
          {% if is_state_attr('camera.front_door', 'motion_detection_enabled', true) %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}