#-------------------------------------------
# Weather Related Packages
# @Backslashh
# Original Repo : https://github.com/backslashh/homeassistant-config
#-------------------------------------------

homeassistant:
  customize:

    sensor.holiday:
      icon: mdi:beach
      friendly_name: Holiday

###############################################################################
# Sensor updates once every 4 hours (14400 seconds) & runs 6 times in 24 hours
#
# First it checks for holiday in static section, if that doesn't exist,
# it checks in the dynamic section. If neither exists, the value will be empty
###############################################################################
sensor:
  - platform: rest
    resource: https://raw.githubusercontent.com/Backslashh/homeassistant-config/master/json_data/holidays.json
    name: Holiday
    scan_interval: 14400
    value_template: >
      {% set today = now().day  ~ '/' ~ now().month  %}
      {% set holiday =  value_json.MAJOR_AU.static[ today ] %}
      {% if holiday | trim == "" %}
        {% set today = now().day  ~ '/' ~ now().month ~ '/' ~ now().year %}
        {% set holiday =  value_json.MAJOR_AU.dynamic[ today ] %}
      {% endif %}
      {{ holiday }}

  ################################################################################
  # Countdown Sesor using WolfRam Alpha Natural language queries
  ################################################################################

  - platform: rest
    name: Halloween Countdown
    resource: !secret wolframalpha_halloween_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Christmas Countdown
    resource: !secret wolframalpha_xmas_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Easter Countdown
    resource: !secret wolframalpha_easter_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Em Birthday Countdown
    resource: !secret wolframalpha_embirthday_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Will Birthday Countdown
    resource: !secret wolframalpha_willbirthday_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200
  
  - platform: rest
    name: Teddy Birthday Countdown
    resource: !secret wolframalpha_teddybirthday_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Ollie Birthday Countdown
    resource: !secret wolframalpha_olliebirthday_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200
  
###############################################################################
# Automation that notifies of a Holiday "state" change
###############################################################################
automation:
  - alias: Notify Holiday State Change

    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.holiday
    condition:
      - condition: template
        value_template: "{{ states('sensor.holiday') != 'unknown' }}"
      - condition: template
        value_template: "{{ states.sensor.holiday.state | trim != '' }}"
    action:
      - service: persistent_notification.create
        data:
          message: 'Today is {{ states.sensor.holiday.state }}.'
          title: '{{ states.sensor.holiday.state }}'
  