#-------------------------------------------
# Ollie's Medicine Related Packages
# @Backslashh
# Original Repo : https://github.com/backslashh/homeassistant-config
#-------------------------------------------

homeassistant:
  customize:
    
    binary_sensor.morning_meds_taken:
      friendly_name: Morning meds taken?
      icon: mdi:pill
    binary_sensor.evening_meds_taken:
      friendly_name: Evening meds taken?
      icon: mdi:pill
    binary_sensor.bedtime_meds_taken:
      friendly_name: Bedtime meds taken?
      icon: mdi:pill
    
###############################################################################
# Binary Sensors for displaying if Medicines have been taken
###############################################################################
binary_sensor:
  - platform: template
    sensors:
      morning_meds_taken:
        friendly_name: Morning Meds Taken
        entity_id: input_boolean.morning_meds_taken
        value_template: >-
          {% if is_state('input_boolean.morning_meds_taken', 'on') %}
            Yes
          {% else %}
            No
          {% endif %}
      evening_meds_taken:
        friendly_name: Evening Meds Taken
        entity_id: input_boolean.evening_meds_taken
        value_template: >-
          {% if is_state('input_boolean.evening_meds_taken', 'on') %}
            Yes
          {% else %}
            No
          {% endif %}
      bedtime_meds_taken:
        friendly_name: Bedtime Meds Taken
        entity_id: input_boolean.bedtime_meds_taken
        value_template: >-
          {% if is_state('input_boolean.bedtime_meds_taken', 'on') %}
            Yes
          {% else %}
            No
          {% endif %}

#################################################################
## Medication Reminder
#################################################################   
automation:

  - id: 'reset_meds_taken'
    alias: Reset morning meds taken
    trigger:
      platform: time
      at: 00:00:00
    action:
      service: input_boolean.turn_off
      data:
        entity_id: 
          - input_boolean.morning_meds_taken
          - input_boolean.evening_meds_taken
          - input_boolean.bedtime_meds_taken

  - id: 'mark_morning_meds_taken'
    alias: Mark morning meds as taken
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'confirm_morning_meds'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.morning_meds_taken
      - service: notify.all_devices
        data:
          message: clear_notification
          data:
            tag: morning_meds

  - id: 'mark_evening_meds_taken'
    alias: Mark evening meds as taken
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'confirm_evening_meds'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.evening_meds_taken
      - service: notify.all_devices
        data:
          message: clear_notification
          data:
            tag: evening_meds
      
  - id: 'mark_bedtime_meds_taken'
    alias: Mark bedtime meds as taken
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: 'confirm_bedtime_meds'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedtime_meds_taken
      - service: notify.all_devices
        data:
          message: clear_notification
          data:
            tag: bedtime_meds

  - id: 'morning_meds_notification'
    alias: Morning meds Notificaiton
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.morning_meds_taken
        state: 'off'
    action:
      - service: notify.all_devices
        data:
          message: "Ollie needs Carvidilol (1.5ml), Aspirin (1.7ml) and Fruzi (1ml)"
          data:
            actions: 
              - action: "confirm_morning_meds"
                title: "Confirm"
            tag: morning_meds
            ttl: 0
            priority: high
            channel: Medication
            color: purple

  - id: 'morning_meds_reminder'
    alias: Morning meds reminder
    trigger:
      platform: time_pattern
      minutes: '/30'
    condition:
      - condition: state
        entity_id: input_boolean.morning_meds_taken
        state: 'off'
      - condition: time
        after: '08:30:00'
        before: '23:59:00'
    action:
      service: notify.all_devices
      data:
        message: "It looks like Ollie hasn't had his morning meds. Please make sure he has them."
        data:
          actions: 
            - action: "confirm_morning_meds"
              title: "Confirm"
          tag: morning_meds
          ttl: 0
          priority: high
          channel: Medication
          color: purple

  - id: 'evening_meds_notification'
    alias: Evening meds Notificaiton
    trigger:
      platform: time
      at: "18:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.evening_meds_taken
        state: 'off'
    action:
      - service: notify.all_devices
        data:
          message: "Ollie needs Lisinopril (3ml)"
          data:
            actions: 
              - action: "confirm_evening_meds"
                title: "Confirm"
            tag: evening_meds
            ttl: 0
            priority: high
            channel: Medication
            color: purple

  - id: 'evening_meds_reminder'
    alias: Evening meds reminder
    trigger:
      platform: time_pattern
      minutes: '/30'
    condition:
      - condition: state
        entity_id: input_boolean.evening_meds_taken
        state: 'off'
      - condition: time
        after: '18:30:00'
        before: '23:59:00'
    action:
      service: notify.all_devices
      data:
        message: "It looks like Ollie hasn't had his evening meds. Please make sure he has them."
        data:
          actions: 
            - action: "confirm_evening_meds"
              title: "Confirm"
          tag: evening_meds
          ttl: 0
          priority: high
          channel: Medication
          color: purple

  - id: 'bedtime_meds_notification'
    alias: Bedtime meds Notificaiton
    trigger:
      platform: time
      at: "19:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.bedtime_meds_taken
        state: 'off'
    action:
      - service: notify.all_devices
        data:
          message: "Ollie needs Carvidilol (1.5ml)"
          data:
            actions:
              - action: "confirm_bedtime_meds"
                title: "Confirm"
            tag: bedtime_meds
            ttl: 0
            priority: high
            channel: Medication
            color: purple

  - id: 'bedtime_meds_reminder'
    alias: Bedtime meds reminder
    trigger:
      platform: time_pattern
      minutes: '/30'
    condition:
      - condition: state
        entity_id: input_boolean.bedtime_meds_taken
        state: 'off'
      - condition: time
        after: '20:00:00'
        before: '23:59:00'
    action:
      service: notify.all_devices
      data:
        message: "It looks like Ollie hasn't had his bedtime meds. Please make sure he has them."
        data:
          actions: 
            - action: "confirm_bedtime_meds"
              title: "Confirm"
          tag: bedtime_meds
          ttl: 0
          priority: high
          channel: Medication
          color: purple