---
    name: Yaml Lint
    on: [push]
    jobs:
      FixIt:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: yaml-lint
            uses: ibiqlik/action-yamllint@master